active_aging_planner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('planning/', include('planning.urls')),
    path('auth/', include('authentication.urls')),
    path('', include('landing.urls')),
]

authentication/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

landing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
]

templates/layout.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Title{% endblock %}</title>
    {% tailwind_css %}
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        primary: '#6F63F2',
                        'primary-dark': '#4E47C4',
                        title: '#2B3240',
                        text: '#5C6575',
                    }
                }
            }
        }
    </script>
    {% block javascript %}
    {% endblock %}
</head>
<body class="bg-gray-100">
    <header class="w-full bg-indigo-500 p-2 text-white">
        <nav class="container mx-auto flex justify-end gap-x-3 px-4">
            <a href="{% url 'landing_page' %}">Home</a>
            {% if user.is_authenticated %}
                | <a href="{% url 'profiles:profile' %}">Telas</a>
                | <a href="{% url 'dashboard:index' %}">Dashboard</a>
                | <a href="{% url 'projects:manage_actions_matrix' %}">Ações</a>
                | <a href="{% url 'papers:index' %}">Artigos científicos</a>
                | <a href="{% url 'help:index' %}">Ajuda</a>
                | <form action="{% url 'auth:logout' %}" method="post" class="inline">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            {% else %}
                | <a href="{% url 'auth:login' %}">Login</a>
            {% endif %}
        </nav>
    </header>
    {% block content %}
    {% endblock %}
</body>
</html>